#!/bin/bash
printf "\e[1;32m\e[44m>>cybersoloit-framework is updating\e[0m\n"
printf "\e[1;33mplease wait\e[0m"
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m\n"
dty=$(pwd)
#<<<------DISTRO VERIFICATION------>>>
cd $HOME
distro=$(pwd)
if [[ $distro == /data/data/com.termux/files/home ]]
then
cd .. && cd usr/bin
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]
then
cd .. && cd bin
else
cd /usr/bin
fi
#<<<-----remove payload generator----->>>
echo
printf "\e[1;32m REMOVING OLD VERSION IF FOUND\e[0m\n"
echo
printf "\e[1;33mplease wait\e[0m"
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m\n"
__oldremove__() {
if [[ $distro == /data/data/com.termux/files/home || $distro == /data/data/hilled.pwnterm/files/usr/home ]]; then
bhu=$(find .paygen)
if [[ $bhu == .paygen ]]
then
rm -rf .paygen
printf "\e[1;90m ONE old Hidden file deleted :)\e[0m\n"
else
#printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 0.125
fi
#<<<------remove payload binder------->>>
jisu=$(find .binderr)
if [[ $jisu == .binderr ]]
then
rm -rf .binderr
printf "\e[1;90m ONE old Hidden file deleted :)\e[0m\n"
else
#printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 0.125
fi
#<<<------remove lemon  binder------>>>
lemon=$(find .lembinder)
if [[ $lemon == .lembinder ]]
then
rm -rf .lembinder
printf "\e[1;90m ONE old Hidden file deleted :)\e[0m\n"
else
printf "\e[1;90mNo any old hidden files found to remove :)\e[0m\n"
sleep 0.125
fi
#<<<------remove csfconsole------->>>
jk=$(find csfconsole)
if [[ $jk == csfconsole ]]
then
rm -rf csfconsole
else
printf "\e[1;90myou may installing cybersploit-framework first time :)\e[0m\n"
echo
printf "\e[1;91mThank you for installing our cybersploit-framework :)\e[0m\n"
sleep 0.125
fi
#<<<------remove cybersploit-u------>>>
suman=$(find cybersploit-u)
if [[ $suman == cybersploit-u ]]
then
rm -rf cybersploit-u
printf "\e[1;97m\e[41mOld version is removing ;)\e[0m\n"
else
printf "\e[1;97m\e[41mNo old version found to remove\e[0m\n"
fi

else

bhu=$(find .paygen)
if [[ $bhu == .paygen ]]
then
rm -rf .paygen
printf "\e[1;90m ONE old Hidden file deleted :)\e[0m\n"
else
#printf "\e[1;90mNo any hidden files found to remove \e[0m\n"
sleep 0.125
fi
#<<<------remove payload binder------->>>
jisu=$(find .binderr)
if [[ $jisu == .binderr ]]
then
sudo rm -rf .binderr
printf "\e[1;90m ONE old Hidden file deleted :)	\e[0m\n"
else
#printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 0.125
fi
#<<<------remove lemon  binder------>>>
lemon=$(find .lembinder)
if [[ $lemon == .lembinder ]]
then
sudo rm -rf .lembinder
printf "\e[1;90m ONE old Hidden file deleted\e[0m\n"
else
#printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 0.125
fi
#<<<------remove csfconsole------->>>
jk=$(find csfconsole)
if [[ $jk == csfconsole ]]
then
sudo rm -rf csfconsole
else
printf "\e[1;90myou may installing cybersploit-framework first time :)\e[0m\n"
echo
printf "\e[1;91mThank you for installing our cybersploit-framework :)\e[0m\n"
sleep 0.125
fi
#<<<------remove cybersploit-u------>>>
suman=$(find cybersploit-u)
if [[ $suman == cybersploit-u ]]
then
sudo rm -rf cybersploit-u
printf "\e[1;97m\e[41mOld version is removing ;)\e[0m\n"
else
printf "\e[1;97m\e[41mNo old version found to remove\e[0m\n"
fi
fi

#<<<------remove cybersploit-framework------>>>
echo
printf "\e[1;34m\e[46mplease do not stop here the process by any chance otherwise so sad for you\e[0m\n"
sleep 0.125
cd $dty && cd ..
jithu=$(find cybersploit-framework)
if [[ $jithu == *'cybersploit-framework'* ]]
then
rm -rf *cybersploit-framework*
else
#printf "\e[1;35mOld version is completely removed\e[0m\n"
sleep 0.125
fi
printf "\e[1;35mOld version is completely removed if found ;)\e[0m\n"
sleep 0.7
}
__oldremove__ > /dev/null 2>&1
#<<<------downloading latest cybersploit-framework------>>>
printf "\e[1;32mInstalling latest version\e[0m"
sleep 0.5
printf "\e[1;32m.\e[0m"
sleep 0.2
printf "\e[1;32m.\e[0m"
sleep 0.2
printf "\e[1;32m.\e[0m"
sleep 0.2
printf "\e[1;32m.\e[0m\n"
git clone https://github.com/jithu1234b/cybersploit-framework
if [[ $distro == /data/data/com.termux/files/home ]];then
mv -v cybersploit-framework /data/data/com.termux/files/usr/share
cd /data/data/com.termux/files/usr/share
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]; then
mv -v cybersploit-framework /data/data/hilled.pwnterm/files/usr/share
cd /data/data/hilled.pwnterm/files/usr/share
else
sudo mv -v cybersploit-framework /usr/share
cd /usr/share
fi
#<<<------adding permissions to programs------>>>
cd cybersploit-framework
chmod u+x *
ls -a
chmod u+x .paygen
chmod u+x .binderr
chmod u+x .lembinder
#<<<------installing requirements for cybersploit-framework------>>>
printf "\e[1;31m\e[45mchecking and installing requirements\e[0m\n"
sleep 0.25
bash requirements
#<<<----moving programs in bin directory for TERMUX------>>>
if [[ $distro == /data/data/com.termux/files/home ]]
then
ln -sf /data/data/com.termux/files/usr/share/cybersploit-framework/csfconsole /data/data/com.termux/files/usr/bin/csfconsole
ln -sf /data/data/com.termux/files/usr/share/cybersploit-framework/cybersploit-u /data/data/com.termux/files/usr/bin/cybersploit-u
ln -sf /data/data/com.termux/files/usr/share/cybersploit-framework/.paygen /data/data/com.termux/files/usr/bin/.paygen
ln -sf /data/data/com.termux/files/usr/share/cybersploit-framework/.binderr /data/data/com.termux/files/usr/bin/.binderr
ln -sf /data/data/com.termux/files/usr/share/cybersploit-framework/.lembinder /data/data/com.termux/files/usr/bin/.lembinder
#<<<------moving programs in bin directory for PWN-TERM------>>>
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]
then
ln -sf /data/data/hilled.pwnterm/files/usr/share/cybersploit-framework/csfconsole /data/data/hilled.pwnterm/files/usr/bin/csfconsole
ln -sf /data/data/hilled.pwnterm/files/usr/share/cybersploit-framework/cybersploit-u /data/data/hilled.pwnterm/files/usr/bin/cybersploit-u
ln -sf /data/data/hilled.pwnterm/files/usr/share/cybersploit-framework/.paygen /data/data/hilled.pwnterm/files/usr/bin/.paygen
ln -sf /data/data/hilled.pwnterm/files/usr/share/cybersploit-framework/.binderr /data/data/hilled.pwnterm/files/usr/bin/.binderr
ln -sf /data/data/hilled.pwnterm/files/usr/share/cybersploit-framework/.lembinder /data/data/hilled.pwnterm/files/usr/bin/.lembinder
else
sudo ln -sf /usr/share/cybersploit-framework/csfconsole /usr/bin/csfconsole
sudo ln -sf /usr/share/cybersploit-framework/cybersploit-u /usr/bin/cybersploit-u
sudo ln -sf /usr/share/cybersploit-framework/.paygen /usr/bin/.paygen
sudo ln -sf /usr/share/cybersploit-framework/.binderr /usr/bin/.binderr
sudo ln -sf /usr/share/cybersploit-framework/.lembinder /usr/bin/.lembinder
fi
cd $HOME
clear
#<<<------user guide after installation------>>>
printf "\e[1;32m\e[104mLatest vesion of cybersploit is installed\e[0m\n"
printf "\n"
printf "\e[1;36mRun:- 'csfconsole' to use it\e[0m\n"
echo
printf "\e[1;31m\e[104mEver you want to update just Run 'cybersploit-u'\e[0m\n"
echo
printf "\e[1;96mIf you liked it then please give us a star '✰' on github :)\e[0m\n"
printf "\e[1;91mTHANK YOU!!!\e[0m\n"
echo
printf "\e[1;97mplease run 'cd \$HOME' if 'ls' command gives any error\e[1;0m\n"


#Direct link for cybersploit installation FOR TERMUX AND PWN-TERM USER:- (" bash <(curl -fsSL "https://bit.ly/3jwvC0N") -i ")
#Written by:- JK && Suman Kumar ~BHUTUU



#<<<-----xxxxx-----xxxxx-----END-----xxxxx-----xxxxx----->>>
