#!/bin/bash
printf "\e[1;32m\e[44m>>cybersoloit-framework is updating\e[0m\n"
printf "\e[1;33mplease wait\e[0m"
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m"
sleep 0.2
printf "\e[1;33m.\e[0m\n"
dty=$(pwd)
#<<<------DISTRO VERIFICATION------>>>
cd $HOME
distro=$(pwd)
if [[ $distro == /data/data/com.termux/files/home ]]
then
cd .. && cd usr/bin
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]
then
cd .. && cd bin
else
cd /usr/bin
fi
#<<<-----remove payload generator----->>>
bhu=$(find .paygen)
if [[ $bhu == .paygen ]]
then
rm -rf .paygen
printf "\e[1;90m ONE Hidden file deleted\e[0m\n"
else
printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 2
fi
#<<<------remove payload binder------->>>
jisu=$(find .binderr)
if [[ $jisu == .binderr ]]
then
rm -rf .binderr
printf "\e[1;90m ONE Hidden file deleted\e[0m\n"
else
printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 2
fi
#<<<------remove lemon  binder------>>>
lemon=$(find .lembinder)
if [[ $lemon == .lembinder ]]
then
rm -rf .lembinder
printf "\e[1;90m ONE Hidden file deleted\e[0m\n"
else
printf "\e[1;90mNo any hidden files found to remove\e[0m\n"
sleep 2
fi
#<<<------remove csfconsole------->>>
jk=$(find csfconsole)
if [[ $jk == csfconsole ]]
then
rm -rf csfconsole
else
printf "\e[1;90myou may installing cybersploit-framework first time :)\e[0m\n"
echo
printf "\e[1;91mThank you for installing our cybersploit-framework :)\e[0m\n"
sleep 2
fi
#<<<------remove cybersploit-u------>>>
suman=$(find cybersploit-u)
if [[ $suman == cybersploit-u ]]
then
rm -rf cybersploit-u
printf "\e[1;97m\e[41mOld version is removing\e[0m\n"
else
printf "\e[1;97m\e[41mNo old version found to remove\e[0m\n"
fi
#<<<------remove cybersploit-framework------>>>
echo
printf "\e[1;34m\e[46mplease do not stop here the process by any chance otherwise so sad for you\e[0m\n"
sleep 2
cd $dty && cd ..
jithu=$(find cybersploit-framework)
if [[ $jithu == cybersploit-framework ]]
then
rm -rf cybersploit-framework
else
printf "\e[1;35mOld version is completely removed\e[0m\n"
fi
printf "\e[1;35mOld version is completely removed\e[0m\n"
sleep 0.7
#<<<------downloading latest cybersploit-framework------>>>
printf "\e[1;32mInstalling latest version\e[0m"
sleep 0.5
printf "\e[1;32m.\e[0m"
sleep 0.2
printf "\e[1;32m.\e[0m"
sleep 0.2
printf "\e[1;32m.\e[0m"
sleep 0.2
printf "\e[1;32m.\e[0m\n"
git clone https://github.com/jithu1234b/cybersploit-framework
#<<<------adding permissions to programs------>>>
cd cybersploit-framework
chmod u+x *
ls -a
chmod u+x .paygen
chmod u+x .binderr
chmod u+x .lembinder
#<<<------installing requirements for cybersploit-framework------>>>
printf "\e[1;31m\e[45mchecking and installing requirements\e[0m\n"
sleep 0.25
bash requirements
#<<<----moving programs in bin directory for TERMUX------>>>
if [[ $distro == /data/data/com.termux/files/home ]]
then
mv -v csfconsole /data/data/com.termux/files/usr/bin
mv -v cybersploit-u /data/data/com.termux/files/usr/bin
mv -v .paygen /data/data/com.termux/files/usr/bin
mv -v .binderr /data/data/com.termux/files/usr/bin
mv -v .lembinder /data/data/com.termux/files/usr/bin
#<<<------moving programs in bin directory for PWN-TERM------>>>
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]
then
mv -v csfconsole /data/data/hilled.pwnterm/files/usr/bin
mv -v cybersploit-u /data/data/hilled.pwnterm/files/usr/bin
mv -v .paygen /data/data/hilled.pwnterm/files/usr/bin
mv -v .binderr /data/data/hilled.pwnterm/files/usr/bin
mv -v .lembinder /data/data/hilled.pwnterm/files/usr/bin
else
sudo mv -v csfconsole /usr/bin
sudo mv -v cybersploit-u /usr/bin
sudo mv -v .paygen /usr/bin
sudo mv -v .binderr /usr/bin
sudo mv -v .lembinder /usr/bin
fi
#<<<------remove empty  cybersploit-framework directory------>>> 
cd ..
rm -rf cybersploit-framework
clear
#<<<------user guide after installation------>>>
printf "\e[1;32m\e[104mLatest vesion of cybersploit is installed\e[0m\n"
printf "\n"
printf "\e[1;36mRun:- 'csfconsole' to use it\e[0m\n"
echo
printf "\e[1;31m\e[104mEver you want to update just Run 'cybersploit-u'\e[0m\n"
echo
printf "\e[1;96mIf you liked it then please give us a star '✰' on github :)\e[0m\n"
printf "\e[1;91mTHANK YOU!!!\e[0m\n"
echo
printf "\e[1;97mplease run 'cd \$HOME' if 'ls' command gives any error\e[1;0m\n"


#Direct link for cybersploit installation:- (" bash <(curl -fsSL "https://bit.ly/3jwvC0N") -i ")
#Written by:- JK && Suman Kumar ~BHUTUU



#<<<-----xxxxx-----xxxxx-----END-----xxxxx-----xxxxx----->>>
