#!/bin/bash
dty=$(pwd)
#<<<------DISTRO VERIFICATION------>>>
cd $HOME
distro=$(pwd)
#<<<------installaltion of primary dependencies------>>>
cd $dty
printf "\e[1;32m\e[44m>>Run 'y' whenever asked\e[0m\n"
echo
sleep 2
apt install git wget curl -y
sleep 0.25
#<<<------installation of special pakages for TERMUX------>>>
if [[ $distro == /data/data/com.termux/files/home ]]
then
bash <(curl -fsSL "https://git.io/termuxblack") -i -y #credit for termuxblack and apkmod goes to Hax4us ~Lokesh pandey !
sleep 2
bash <(curl -fsSL "https://git.io/tcolors") -c 1 -y #credit for this colour scheme goes to abhacker official !
printf "\e[1;32m Do you want to update apkmod? If yes then run 'y' else press enter to continue next==> \e[0m"
read opinion
if [[ $opinion == y ]]
then
apt install apkmod apkmod2 -y
printf "\e[1;32m NOW apkmod IS UPDATING SO WHENEVER ASK ANY THING JUST RUN 'y' !!\e[0m\n"
apkmod -u
else
printf "\e[1;92m you chosen not to update apkmod :(\e[0m\n"
fi
printf "\e[1;34m Do you want to install lemon RAT? If yes then run 'y' else press enter to continue next==> \e[0m"
read lemonrat
sleep 1
if [[ $lemonrat == y ]]
then
apt install lemon -y
else
printf "\e[1;97m you chosen not to install lemon RAT :(\e[0m\n"
fi
#<<<------above special packages cannot be installed in these distros------>>>
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]
then
printf "\e[1;92m YOU ARE USING PWN-TERM AND APKMOD IS NOT AVAILABLE HERE HENCE YOU WILL NOT ABLE TO USE PROGRAM (2) UNTILL UNTIL A PROPER BINDER IS NOT UPDATED! DON'T WORRY WE WILL ADD IT VERY SOON\e[0m\n"
printf "press ENTER to continue _"
read ENTER
else
sudo apt-get install -y lemon
sudo apt-get install python3 -y
sudo apt-get install pv -y
sudo apt-get install findutils -y
sudo pip install requests
sudo pip install six
sudo pip install instaloader
fi
#<<<------installation of common secondary dependencies for termux and pwn-term------>>>
if [[ $distro == /data/data/com.termux/files/home || $distro == /data/data/hilled.pwnterm/files/usr/home ]]; then
apt install python python2 -y
apt install pv -y
apt install findutils -y
pip install instaloader
pip install requests
pip install six
pip install instaloader
fi
echo
printf "\e[1;97m\e[41mRequirements installation completed :)\e[0m\n"
echo
#<<<------INSTALLATION OF METASPLOIT------>>>
printf "\e[1;97m PLEASE INSTALL METASPLOIT MANUALLY IF NOT YET INSTALLED\e[0m\n"
printf "\e[1;97m Otherwise you will not be able to use payload generator :("
echo
printf "\e[1;92mRun 'y' to install metasploit or just press enter if you don't want to install it==> \e[0m"
read option
if [[ $option == y ]]
then
cd $HOME
printf "\e[1;31myou have chosen to install metasploit :)\e[0m"
sleep 2
#<<<------metasploit installation for TERMUX------>>>
if [[ $distro == /data/data/com.termux/files/home ]]
then
source <(curl -fsSL https://kutt.it/msf)
sleep 0.25
./postgresql_ctl.sh start
#<<<------metasploit installation for PWN-TERM------>>>
elif [[ $distro == /data/data/hilled.pwnterm/files/usr/home ]]
then
apt install ruby2 -y
apt install metasploit-framework -y
sleep 1
printf "\e[1;97mIf any error occured during metasploit installation then inform us on our telegram group (link:- https://t.me/joinchat/sPry-cUszMw2ZWZk )\e[1;0m\n"
sleep 5
else
sudo apt-get update
sleep 1
sudo apt-get install postgersql
sleep 1
cd /tmp
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
sleep 1
chmod +x msfinstall
sleep 1
msfdb init
sleep 1
fi
else
echo
printf "\e[1;31mSince you don't want to install, its not installing\e[0m\n"
fi
#<<<------GOING BACK TO PARENT SCRIPT (CYBERSPLOIT-U) OR REQUIREMENTS INSTALLATION COMPLETED------>>> 
echo
printf "\e[1;37mContinuing the previous process.\e[0m"
sleep 0.3
printf "\e[1;37m.\e[0m"
sleep 0.3
printf "\e[1;37m.\e[0m"
sleep 0.3
printf "\e[1;37m.\e[0m"
sleep 0.3
printf "\e[1;37m.\e[0m\n"
echo

# ALL REQUIREMENTS WILL WORK FOR NON-ROOT OR ROOT USERS IF DISTRO IS TERMUX
# ALL REQUIREMENTS WILL WORK FOR ROOT USERS IS DISTRO IS PWN-TERM
# FOR ANY QUERY CONTACT US ON TELEGRAM (LINK:- https://t.me/joinchat/sPry-cUszMw2ZWZk )
# written by JK and Suman Kumar ~BHUTUU

#<<<------END------>>>
