#!/data/data/com.termux/files/usr/bin/bash
printf "\e[1;32m\e[44m>>Run 'y' whenever asked\e[0m\n"
echo
sleep 2
apt install git wget curl -y
sleep 0.25
bash <(curl -fsSL "https://git.io/tcolors") -c 1 -y #credit for this colour scheme goes to abhacker official !
apt install python python2 -y
apt install findutils -y
pip install instaloader
pip install requests
pip install six
echo
printf "\e[1;97m\e[41mRequirements installation completed :)\e[0m\n"
echo
printf "\e[1;97m PLEASE INSTALL METASPLOIT MANUALLY IF NOT YET INSTALLED\e[0m")
printf "\e[1;97m Otherwise you will not be able to use payload generator :("
echo

